name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "hola" ] # Cambia "CI" por el nombre de tu flujo de trabajo
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      # Agregar una acci칩n de notificaci칩n (Este es un ejemplo b치sico)
      - name: Notify team
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const members = await github.teams.listMembersInOrg({
              org: "Aaaprueba", // Reemplazar <ORG_NAME> por el nombre de tu organizaci칩n
              team_slug: "Equipo", // Reemplazar <TEAM_SLUG> por el slug de tu equipo
            });
            const usernames = members.data.map(member => member.login);
            const notifications = usernames.map(username => {
              return github.activity.createThread({
                subject_type: "Repository",
                subject_id: context.repo.repo,
                thread_title: "Workflow completed",
                recipients: [username],
                text: "The workflow has completed successfully.",
              });
            });
            await Promise.all(notifications);
